review setup charkra UI
killerburn69/renis-client pull request #1
Opened 2023-01-06 03:20 UTC by killerburn69

các công việc đã làm:
+ setup chakraUI (em lần đầu setup nên có gì anh review nặng để em bik)
+ layout Signin, Signup (chưa responsive), để coi đc dùng chuyển router localhost:3000/signin (or /signup)
+ tạo các component

2023-01-06 04:20 UTC, phanhuutoan requested changes
1. Cái gì không cần phải custom lại thì ko cần phải custom lại, cứ dùng những cái sẵn có của họ, việc custom lại hoàn toàn rất tốn effort mà ko cần thiết (như lightHeight, letterSpacing,...) 
2. Có một số chỗ có thể dùng custom component tại sao phải dùng chakra factory, có ý nghĩa gì không, chakra factory chủ yếu hỗ trợ tạo ra component và đồng thời có thể sử dụng props as css, a ko thấy e dùng nhiều lắm.

2023-01-06 04:20 UTC, phanhuutoan commented on package.json
> +    "formik": "^2.2.9",
đổi sang react-hook-form

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/Button.tsx
> +interface ButtonProps {
extends lại ButtonProps có sẵn của chakraUI Button chứ viết vậy ko tận dụng đc Props sẵn có của nó

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/Inputs.tsx
> +const Inputs = ({label,placeholder,type,id}:FormInput) => {
cài đặt ESlint cho code nhìn đẹp hơn

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/Inputs.tsx
> +}
Extends lại props của component chakraUI

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/RightBackground.tsx
> +              <Text color={'white'} fontSize={32} fontWeight={'semibold'} marginBottom={'1'}>Rensis</Text>
sử dụng layerStyle của chakraUI để consistent style cho text

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/RightBackground.tsx
> +              <Text color={'white'}>Version 1.0</Text>
sử dụng layerStyle của chakraUI để consistent style cho text

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/Wrapper.tsx
> +interface IWrapperProps{
extends PropsWithChildren của react thay vì truyền children vào

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/Wrapper.tsx
> +    </Grid>
cố định 2 cột thôi à? v thì cân nhắc đặt tên lại component Wrapper

2023-01-06 04:20 UTC, phanhuutoan commented on src/index.css
> +/* body {
xóa luôn file này đi

2023-01-06 04:20 UTC, phanhuutoan commented on src/pages/Signin/Signin.tsx
> +            <Text fontSize={28} fontWeight={'semibold'} marginBottom={'8'}>
chuyển thành textStyle for consistent đọc thêm chakraUI
Ref: https://chakra-ui.com/docs/styled-system/text-and-layer-styles#layer-styles

2023-01-06 04:20 UTC, phanhuutoan commented on src/components/Button.tsx
> +const Buttons = ({ width, size, content, type }: ButtonProps) => {
Cân nhắc sử dụng ButtonTheme của chakraUI thay vì tạo button mới
Ref: https://chakra-ui.com/docs/components/button/theming

2023-01-06 04:20 UTC, phanhuutoan commented on src/pages/Signin/Signin.tsx
> +                <Flex justifyContent={'space-between'} marginBottom={'8'}>
Cố gắng sử dụng shortTerm property như là `justify `và `mb`

2023-01-06 04:20 UTC, phanhuutoan commented on src/theme/background/background.ts
> +export const Background =  chakra('div',{
Tại sao ko tạo 1 component mà lại dùng chakra factory? có vấn đề gì không

2023-01-06 04:20 UTC, phanhuutoan commented on src/theme/background/background.ts
> +export const BackgroundCustom = chakra('div',{
Tương tự tại sao ko dùng component mà dùng factory

2023-01-06 04:20 UTC, phanhuutoan commented on src/theme/borderRadius/borderRadius.ts
> +export const borderRadius = {
Borderadius có sẵn ko xài được hay sao phải custom lại

2023-01-09 08:20 UTC, phanhuutoan approved these changes
LGTM

2023-01-09 08:20 UTC, phanhuutoan commented on src/components/Mainbackground.tsx
> +      alignItems="center"
`<Box sx={boxStyle} />`
```js
boxStyle = {
  bg: primary.200
}
```

2023-01-09 08:20 UTC, phanhuutoan commented on src/pages/Signin/Signin.tsx
> -        <Wrapper>
CustomWrapv2

2023-01-09 16:07 UTC, vinhprs commented
Approved

2023-01-09 16:08 UTC, merged