review Homepage UI
killerburn69/renis-client pull request #2
Opened 2023-01-30 08:40 UTC by killerburn69

Những phần đã làm ở branch này:
+ Navbar component
+ Search component
+ Homepage ( BoxImage.tsx, CardMain.tsx, ToastAccept.tsx, ToastReject.tsx)
+ modify in theme folder

2023-01-30 15:54 UTC, vinhprs approved these changes
Approved

2023-01-31 03:54 UTC, phanhuutoan requested changes
### Code tốt nhưng khá nhiều chỗ cần phải sửa, nhiều chỗ refactor. 
1. Làm video rất chỉn chu, a có lời khen.
2. 
![image](https://user-images.githubusercontent.com/73571447/215655705-170ec614-41b2-4dd6-afde-63f5b4e62e82.png)
Code so vs design chưa chuẩn e cần xem lại chỗ này. 
3. Thay vì dùng SVG chay như vậy hãy sử dụng chức năng tạo icon của chakraUI: https://chakra-ui.com/docs/components/icon/usage, dễ sử dụng và cũng hiệu quả hơn rất nhiều

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/BoxImage.tsx
> +const BoxImage:React.FC<React.PropsWithChildren> = ({children}) => {
Bỏ cái type đi, nếu đặt như vậy thì sẽ không nhất quán vì mấy comp khác e có đặt type đâu

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/CardMain.tsx
> +         <Flex color='white' py={3} px={5} bg='white' align="center" gap="2" boxShadow="xl" rounded="xl">
Những styling nào mà từ 5 style props cái trở lên e tách ra 1 file riêng mà sử dụng `sx` props của chakraUI

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/CardMain.tsx
> +        </Swiper>
DRY (dont repeat yourself) sử dụng `map`

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/CardMain.tsx
> +import { Box, Flex, Heading, Image, Text,Button, useToast } from '@chakra-ui/react'
Component này  e nên truyền props vào (và để data ở component cha) thay vì hard code như vậy sau này sửa rất mệt

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/CardMain.tsx
> +import { Box, Flex, Heading, Image, Text,Button, useToast } from '@chakra-ui/react'
Nói cách khác là mình define data model cho nó ngay từ đầu luôn, mock là mock như thế ko phải hard code

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/CardMain.tsx
> +            </Flex>
DRY

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/Navbar.tsx
> +    <Box zIndex="dropdown" bg='grey.100' boxShadow="md" position={'sticky'} top='0' left='0'>
sử dụng sx props

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/Navbar.tsx
> +              </Center>
DRY

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/ToastAccept.tsx
> +const ToastAccept:React.FC<React.PropsWithChildren> = ({children}) => {
Consistent component style

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/ToastReject.tsx
> +const ToastReject:React.FC<React.PropsWithChildren> = ({children}) => {
Consistent

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/ToastAccept.tsx
> +import React from 'react'
ToastAccept và ToastReject rất giống nhau e nên làm chung 1 cái duy nhất, rồi tái sử dụng thông qua props (type: accept/reject) sau này có thêm 1 loại toast khác cũng không cần phải tạo thêm.

2023-01-31 03:54 UTC, phanhuutoan commented on src/components/ToastReject.tsx
> +import { Box, Image, Text } from '@chakra-ui/react'
Nhập chung vs toastAccept

2023-01-31 03:54 UTC, phanhuutoan commented on src/index.tsx
>  const root = ReactDOM.createRoot(
sao bỏ cái dòng này đi

2023-01-31 03:54 UTC, phanhuutoan commented on src/pages/ActiveAccount/Active.tsx
>  import React from 'react'
File này đặt tên không rõ ràng, nên đặt tên danh từ không nên đặt tên 1 tính từ như vậy

2023-01-31 03:54 UTC, phanhuutoan commented on src/pages/ActiveAccount/Active.tsx
>  import React from 'react'
Đọc vào cũng ko bik nó có tác dụng gì

2023-01-31 03:54 UTC, phanhuutoan commented on src/pages/ActiveAccount/Active.tsx
> +        <TwoColumn>
Nhiều component lồng nhau vậy có thực sự cần thiết hay ko, xem và tìm cách refactor lại hoặc explain hợp lý

2023-01-31 03:54 UTC, phanhuutoan commented on src/theme/button/Button.ts
>  })
Những button này về cơ bản nó rất đặt biệt, tạo component cho nó luôn chứ ko nên nhập chung như vậy, e còn phải bổ sung các trạng thái như hover, focus, disabled nữa

2023-01-31 03:54 UTC, phanhuutoan commented on src/theme/heading/Heading.ts
> +        "custom":custom,
Đặt tên tối nghĩa

2023-01-31 03:54 UTC, phanhuutoan commented on src/theme/heading/Heading.ts
> +        "customNani":customHeadingBaby,
Đặt tên quá tối nghĩa

2023-01-31 03:54 UTC, phanhuutoan commented on src/theme/heading/Heading.ts
> +        "customNani":customHeadingBaby,
và vđ j mà 2 cái tên và variable ko trùng nhau ?

2023-01-31 03:54 UTC, phanhuutoan commented on src/theme/link/Link.ts
> +        custom:customTheme
đặt tối nghĩa

2023-03-18 03:10 UTC, merged